### ISSUE TITLE
Benchmark results

### ISSUE THREAD

**Issue by richardtop** [zenangst/Differific#6]
Would be nice to see the benchmark results in the Readme.

**Comment by zenangst** [comment]
Hey @richardtop, I did some quick benchmarking using [DeepDiff](https://github.com/onmyway133/DeepDiff) example project but I never made a PR to add it to that repo. I would say that both frameworks have similar performance so if you are curious about performance you could head over to that lib and check its references about performance. And if you don't take my word for it, you can add `Differific` as a library to the example project in `DeepDiff` and run it yourself :)

**Comment by zenangst** [comment]
To sum it up, I haven't added benchmarks as it leads to extra maintence for something that hasn't reached `1.0.0` yet. Would probably look into this in the future, if you want to add it then go ahead :) I'm a bit rusty when it comes to generating valid test data for benchmarking.

**Comment by richardtop** [comment]
@zenangst thanks for a quick reply.
I was planning to go with DeepDiff and was curious to know is there any difference between it and Differific.

**Comment by zenangst** [comment]
Previously when I used `DeepDiff`'s algorithm, it didn't handle updates properly by the way it was implemented. `Differific` aims to solve that issue by going in a slightly different direction. Also, there are some small differences in the extensions of collection and table views.

**Comment by richardtop** [comment]
Got it. As a side note, it would be nice to see what are the differences in the Readme (maybe, a goal for v1).

**Comment by ghost** [comment]
Hi,

Just found this a few minutes ago. Had a look at the demo App to see how it performs. Found this.


```swift
import UIKit
import Differific

class ViewController: UIViewController {

  override func viewDidLoad() {
    super.viewDidLoad()
    view.backgroundColor = UIColor.white
  }
}
```

Haha. Need help? I don't mind putting something together.

**Comment by zenangst** [comment]
@rob-nash hey man, I haven't gotten around to make a demo for the project. The things that are there came from the template that I used for generating the project :)

To use the framework, you would make an instance of the `DiffManager`, pass your old and new hashable models into it and then reload the table or collection view using the changeset.

Something like this (as stated in the README):

```swift
let old = dataSource.models
let new = newCollection
let changes = DiffManager().diff(old, new)
tableView.reload(with: changes, before: { dataSource.models = new })
```

Hope that helps and making a demo is on my list of TODO's when life allows.

**Comment by zenangst** [comment]
@rob-nash hey mate, if you still feel like making a demo that would be much appreciated :)

**Comment by ghost** [comment]
I'll see what I can do this month.

**Comment by zenangst** [comment]
@rob-nash much appreciated mate! But don't stress with it 😎
